# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='Hello World'),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='Bangalore', max_length=250),
        ),
    ]
